---
title: "Untitled"
format: html
---


```{r}
install.packages(
  c(
    "conflicted",
    "crew",
    "palmerpenguins",
    "quarto",
    "tarchetypes",
    "targets",
    "tidyverse",
    "visNetwork"
  )
)

```


## google globaltrends
+ https://github.com/ha-pu/globaltrends
```{r}
# current dev version
if (!requireNamespace("globaltrends"))
    devtools::install_github("ha-pu/globaltrends", build_vignettes = TRUE)

# packages ----
library(dplyr)
library(globaltrends)

# connect to db ----
if (!file.exists("db/globaltrends_db.sqlite"))
    initialize_db()
start_db()

# add new control batch ----
new_control <- add_control_keyword(
    keyword = c("gmail", "map", "translate", "wikipedia", "youtube"))

# add new object batch ----
new_object <- add_object_keyword(keyword = c("manchester united", "real madrid"))

if (FALSE){
    # run control download ----
    download_control(control = new_control)
    download_control_global(control = new_control)

    # run object download ----
    download_object(object = new_object)
    download_object_global(object = new_object)
}

# compute search score ----
compute_score(
    control = new_control,
    object = new_object)
compute_voi(
    control = new_control,
    object = new_object)

# compute degree of internationalization ----
compute_doi(
    control = new_control,
    object = new_object)

# export data ----
out_score <- export_score(keyword = "manchester united")
out_voi <- export_voi(keyword = "manchester united")
out_doi <- export_doi(type = "obs", locations = "countries")

# plot data ----
plot_bar(data = out_score)
plot_ts(data = out_score)
plot_box(data = out_score)

plot_ts(data = out_voi)
plot_box(data = out_voi)

plot_ts(data = out_doi)
plot_box(data = out_doi)

plot_voi_doi(data_voi = out_voi, data_doi = out_doi)

# get abnormal internationalization ----
abnorm_score <- get_abnorm_hist(data = out_score)
plot_bar(data = abnorm_score)
plot_ts(data = abnorm_score)
plot_box(data = abnorm_score)

abnorm_voi <- get_abnorm_hist(data = out_voi)
plot_ts(data = abnorm_voi)
plot_box(data = abnorm_voi)

abnorm_doi <- get_abnorm_hist(data = out_doi)
plot_ts(data = abnorm_doi)
plot_box(data = abnorm_doi)

# disconnect from db ----
disconnect_db()
```
